FROM harbor.loongnix.cn/mirrorloongsoncontainers/loongnix-server:8.3

RUN dnf install -y rpm shadow-utils >> /dev/null \
    && dnf clean all \
    && groupadd -r -g 10000 scanner \
    && useradd --no-log-init -m -r -g 10000 -u 10000 scanner
