FROM harbor.loongnix.cn/mirrorloongsoncontainers/loongnix-server:8.3

RUN dnf install -y tzdata shadow-utils >> /dev/null \
    && dnf clean all \
    && groupadd -r -g 10000 harbor && useradd --no-log-init -r -m -g 10000 -u 10000 harbor
