FROM harbor.loongnix.cn/mirrorloongsoncontainers/loongnix-server:8.3

RUN dnf install -y python3 python3-pip httpd python3-PyYAML python3-jinja2 && dnf clean all
RUN pip3 install pipenv==2020.11.15 -i https://pypi.tuna.tsinghua.edu.cn/simple
