FROM harbor.loongnix.cn/mirrorloongsoncontainers/loongnix-server:8.3

RUN dnf install -y shadow-utils >> /dev/null \
    && dnf clean all \
    && groupadd -r -g 10000 notary \
    && useradd --no-log-init -r -g 10000 -u 10000 notary
