ARG GOLANG
FROM ${GOLANG}

ARG SPECTRAL_VERSION
RUN echo "deb http://10.2.5.28/os/lnd-20.loongarch64 DaoXiangHu-testing main contrib non-free" >/etc/apt/sources.list && \
    apt update && apt install -y npm && \
    npm install -g yarn --registry https://registry.npm.taobao.org && \
    yarn global add @stoplight/spectral-cli@6.0.0

ENTRYPOINT ["/usr/local/bin/spectral"]
CMD ["--version"]
