FROM harbor.loongnix.cn/mirrorloongsoncontainers/loongnix-server:8.3

RUN dnf install -y shadow-utils >> /dev/null \
    && dnf clean all \
    && mkdir -p /etc/registry \
    && groupadd -r -g 10000 harbor && useradd --no-log-init -m -g 10000 -u 10000 harbor