ARG GOLANG
FROM ${GOLANG}

ARG SWAGGER_VERSION
RUN curl -fsSL -o /usr/bin/swagger http://10.130.0.4//github.com/go-swagger/go-swagger/releases/download/${SWAGGER_VERSION}/swagger-linux-loongarch64 && chmod +x /usr/bin/swagger

ENTRYPOINT ["/usr/bin/swagger"]
CMD ["--help"]
